In [4]:
import os
import yaml
import pandas as pd
import glob

In [42]:
import yaml
import pandas as pd

# Load the YAML file
with open("D:/New Proj/2023-10/2023-10-05_05-30-00.yaml", "r") as file:  # Replace with your YAML file path
    data = yaml.safe_load(file)

# Convert the YAML data to a DataFrame
df = pd.DataFrame(data)

# Save the DataFrame as a CSV file
df.to_csv("D:/New Proj/output.csv", index=False)  # Replace with your desired CSV output path

print("YAML data successfully converted to CSV!")

YAML data successfully converted to CSV!

In [44]:
import yaml
import pandas as pd

# Load the YAML file
with open("D:/New Proj/2023-10/2023-10-05_05-30-00.yaml", "r") as file:  # Replace with your YAML file path
    data = yaml.safe_load(file)

# Convert the YAML data to a DataFrame
df = pd.DataFrame(data)

In [46]:
df

,Ticker,close,date,high,low,month,open,volume
0,SBIN,592.15,2023-10-05 05:30:00,594.35,587.10,2023-10,590.00,13248028
1,BAJFINANCE,7850.90,2023-10-05 05:30:00,7914.85,7826.90,2023-10,7914.85,795061
2,TITAN,3216.50,2023-10-05 05:30:00,3231.00,3165.00,2023-10,3173.90,1109881
3,ITC,436.05,2023-10-05 05:30:00,440.50,435.05,2023-10,440.00,10030257
4,TCS,3589.35,2023-10-05 05:30:00,3624.00,3551.20,2023-10,3554.00,2990768
5,LT,3096.05,2023-10-05 05:30:00,3114.90,3032.55,2023-10,3032.55,3413447
6,TATACONSUM,849.64,2023-10-05 05:30:00,858.58,846.97,2023-10,855.42,740770
7,RELIANCE,1157.05,2023-10-05 05:30:00,1164.70,1154.50,2023-10,1159.63,10953682
8,HCLTECH,1235.45,2023-10-05 05:30:00,1253.95,1227.80,2023-10,1249.00,2995200
9,JSWSTEEL,755.50,2023-10-05 05:30:00,762.65,752.90,2023-10,762.00,1459736
10,ULTRACEMCO,8177.45,2023-10-05 05:30:00,8208.80,8125.00,2023-10,8177.00,310506
11,POWERGRID,196.60,2023-10-05 05:30:00,199.50,195.35,2023-10,199.50,14575590
12,INFY,1463.45,2023-10-05 05:30:00,1475.65,1450.20,2023-10,1452.00,7384621
13,TRENT,2047.60,2023-10-05 05:30:00,2058.15,2022.30,2023-10,2022.95,461744
14,BHARTIARTL,928.85,2023-10-05 05:30:00,929.60,919.40,2023-10,925.05,7063132
15,TATAMOTORS,619.60,2023-10-05 05:30:00,621.35,614.65,2023-10,619.00,7893892
16,WIPRO,406.80,2023-10-05 05:30:00,410.40,405.00,2023-10,407.95,4062652
17,TECHM,1205.60,2023-10-05 05:30:00,1223.95,1199.50,2023-10,1214.00,2497613
18,NTPC,233.85,2023-10-05 05:30:00,237.40,232.05,2023-10,237.25,22472389
19,HINDUNILVR,2519.55,2023-10-05 05:30:00,2524.80,2495.35,2023-10,2518.00,1909928
20,APOLLOHOSP,5047.05,2023-10-05 05:30:00,5079.85,5026.65,2023-10,5054.95,363289
21,M&M,1537.95,2023-10-05 05:30:00,1550.80,1513.05,2023-10,1533.00,1991367
22,GRASIM,1882.67,2023-10-05 05:30:00,1901.44,1873.55,2023-10,1889.59,544715
23,ICICIBANK,940.85,2023-10-05 05:30:00,943.95,934.55,2023-10,935.20,10478856
24,ADANIENT,2466.35,2023-10-05 05:30:00,2486.50,2446.40,2023-10,2477.95,1132455
25,ADANIPORTS,825.20,2023-10-05 05:30:00,832.00,820.25,2023-10,830.85,2083505
26,BEL,138.95,2023-10-05 05:30:00,141.35,138.10,2023-10,139.50,15996620
27,BAJAJFINSV,1542.55,2023-10-05 05:30:00,1556.00,1532.30,2023-10,1540.00,1153064
28,EICHERMOT,3443.60,2023-10-05 05:30:00,3453.90,3387.05,2023-10,3405.50,394665
29,COALINDIA,289.35,2023-10-05 05:30:00,290.55,283.90,2023-10,288.80,8687014
30,MARUTI,10210.20,2023-10-05 05:30:00,10271.00,10109.00,2023-10,10182.00,377196
31,INDUSINDBK,1401.85,2023-10-05 05:30:00,1415.40,1394.30,2023-10,1408.70,1647175
32,ASIANPAINT,3206.25,2023-10-05 05:30:00,3232.10,3174.30,2023-10,3210.00,1002610
33,TATASTEEL,125.25,2023-10-05 05:30:00,126.15,124.55,2023-10,125.90,27063441
34,HDFCLIFE,624.35,2023-10-05 05:30:00,627.75,619.90,2023-10,626.00,4050085
35,DRREDDY,1081.45,2023-10-05 05:30:00,1095.00,1080.00,2023-10,1092.00,2058530
36,SUNPHARMA,1119.10,2023-10-05 05:30:00,1128.65,1111.80,2023-10,1124.65,2348562
37,KOTAKBANK,1734.25,2023-10-05 05:30:00,1747.00,1721.15,2023-10,1730.00,2966801
38,SHRIRAMFIN,1837.50,2023-10-05 05:30:00,1872.95,1823.00,2023-10,1852.00,1479477
39,NESTLEIND,2291.87,2023-10-05 05:30:00,2310.72,2277.50,2023-10,2300.50,680000
40,ONGC,182.20,2023-10-05 05:30:00,184.00,181.00,2023-10,181.25,11128340
41,CIPLA,1161.10,2023-10-05 05:30:00,1172.95,1155.25,2023-10,1170.10,1446743
42,BPCL,172.23,2023-10-05 05:30:00,173.88,171.40,2023-10,172.75,7115506
43,BRITANNIA,4533.90,2023-10-05 05:30:00,4548.20,4500.00,2023-10,4540.25,302015
44,SBILIFE,1274.45,2023-10-05 05:30:00,1282.10,1264.95,2023-10,1271.00,979561
45,HINDALCO,470.55,2023-10-05 05:30:00,482.40,468.35,2023-10,473.40,4801287
46,HEROMOTOCO,3016.65,2023-10-05 05:30:00,3048.85,2993.40,2023-10,3020.00,537209
47,AXISBANK,1003.25,2023-10-05 05:30:00,1009.20,988.90,2023-10,1000.00,7950412
48,HDFCBANK,1535.75,2023-10-05 05:30:00,1551.55,1532.60,2023-10,1535.05,24256337
49,BAJAJ-AUTO,5011.05,2023-10-05 05:30:00,5039.30,4925.10,2023-10,4935.00,657876

In [40]:
# Save the DataFrame as a CSV file
df.to_csv("D:/stock_csv/2023-10/2023-10-04_05-30-00", index=False)  # Replace with your desired CSV output path

print("YAML data successfully converted to CSV!")

YAML data successfully converted to CSV!

In [61]:
import yaml
import pandas as pd

# Load the YAML file
with open("D:/New Proj/2023-10/2023-10-05_05-30-00.yaml", "r") as file:  # Replace with your YAML file path
    data = yaml.safe_load(file)

# Convert the YAML data to a DataFrame
df = pd.DataFrame(data)

# Save the DataFrame as a CSV file
df.to_csv("D:/New Proj/output.csv", index=False)  # Replace with your desired CSV output path

print("YAML data successfully converted to CSV!")

YAML data successfully converted to CSV!

In [59]:
df

,Ticker,close,date,high,low,month,open,volume
0,SBIN,594.25,2023-10-06 05:30:00,598.95,592.20,2023-10,593.40,8216780
1,BAJFINANCE,8168.55,2023-10-06 05:30:00,8192.00,7845.00,2023-10,7850.00,2145034
2,TITAN,3309.75,2023-10-06 05:30:00,3319.80,3221.10,2023-10,3230.00,1102120
3,ITC,442.15,2023-10-06 05:30:00,443.60,436.65,2023-10,437.85,8418580
4,TCS,3621.40,2023-10-06 05:30:00,3634.95,3575.05,2023-10,3591.00,2075691
5,LT,3093.70,2023-10-06 05:30:00,3114.95,3073.15,2023-10,3114.95,1898118
6,TATACONSUM,864.01,2023-10-06 05:30:00,866.73,850.43,2023-10,850.43,948330
7,RELIANCE,1159.00,2023-10-06 05:30:00,1162.40,1156.03,2023-10,1158.53,5431026
8,HCLTECH,1237.70,2023-10-06 05:30:00,1256.00,1230.10,2023-10,1252.00,2497711
9,JSWSTEEL,765.20,2023-10-06 05:30:00,771.15,758.65,2023-10,760.35,2026927
10,ULTRACEMCO,8195.45,2023-10-06 05:30:00,8239.65,8151.25,2023-10,8198.00,158491
11,POWERGRID,197.05,2023-10-06 05:30:00,197.45,194.85,2023-10,197.00,12857229
12,INFY,1478.70,2023-10-06 05:30:00,1484.50,1463.30,2023-10,1469.50,3598672
13,TRENT,2072.10,2023-10-06 05:30:00,2091.90,2050.10,2023-10,2055.85,444220
14,BHARTIARTL,926.05,2023-10-06 05:30:00,929.20,924.30,2023-10,929.20,2420855
15,TATAMOTORS,622.45,2023-10-06 05:30:00,627.35,620.00,2023-10,627.00,7922379
16,WIPRO,407.85,2023-10-06 05:30:00,409.80,406.95,2023-10,408.00,3182502
17,TECHM,1216.90,2023-10-06 05:30:00,1223.00,1205.00,2023-10,1207.00,1446719
18,NTPC,235.55,2023-10-06 05:30:00,237.50,233.65,2023-10,234.25,8825123
19,HINDUNILVR,2499.40,2023-10-06 05:30:00,2520.00,2494.00,2023-10,2519.95,1083342
20,APOLLOHOSP,5060.25,2023-10-06 05:30:00,5084.00,5028.80,2023-10,5050.00,407753
21,M&M,1548.85,2023-10-06 05:30:00,1554.00,1540.35,2023-10,1545.00,1743027
22,GRASIM,1895.76,2023-10-06 05:30:00,1898.35,1882.52,2023-10,1882.62,399766
23,ICICIBANK,945.20,2023-10-06 05:30:00,946.55,938.00,2023-10,946.00,6355755
24,ADANIENT,2478.10,2023-10-06 05:30:00,2514.95,2466.05,2023-10,2466.35,1510035
25,ADANIPORTS,830.75,2023-10-06 05:30:00,836.50,826.40,2023-10,830.00,1877058
26,BEL,139.00,2023-10-06 05:30:00,140.50,138.65,2023-10,139.00,4987359
27,BAJAJFINSV,1634.65,2023-10-06 05:30:00,1640.70,1551.05,2023-10,1559.35,7384628
28,EICHERMOT,3450.40,2023-10-06 05:30:00,3464.45,3438.35,2023-10,3443.60,249258
29,COALINDIA,287.80,2023-10-06 05:30:00,291.00,287.00,2023-10,290.95,3741467
30,MARUTI,10302.00,2023-10-06 05:30:00,10333.00,10260.00,2023-10,10283.00,335700
31,INDUSINDBK,1434.80,2023-10-06 05:30:00,1438.00,1401.10,2023-10,1404.95,2167139
32,ASIANPAINT,3195.75,2023-10-06 05:30:00,3217.00,3190.00,2023-10,3214.75,814257
33,TATASTEEL,125.90,2023-10-06 05:30:00,127.00,125.10,2023-10,126.50,21928671
34,HDFCLIFE,630.90,2023-10-06 05:30:00,636.20,622.75,2023-10,624.55,3713370
35,DRREDDY,1084.98,2023-10-06 05:30:00,1097.44,1081.84,2023-10,1087.00,1572990
36,SUNPHARMA,1127.30,2023-10-06 05:30:00,1132.15,1123.10,2023-10,1128.00,1056281
37,KOTAKBANK,1743.90,2023-10-06 05:30:00,1747.00,1730.20,2023-10,1735.30,1992323
38,SHRIRAMFIN,1848.85,2023-10-06 05:30:00,1863.00,1835.00,2023-10,1850.95,1262390
39,NESTLEIND,2291.23,2023-10-06 05:30:00,2306.76,2281.49,2023-10,2298.99,388120
40,ONGC,181.45,2023-10-06 05:30:00,183.50,180.60,2023-10,183.50,5759904
41,CIPLA,1163.00,2023-10-06 05:30:00,1181.70,1160.45,2023-10,1165.00,928951
42,BPCL,173.60,2023-10-06 05:30:00,174.50,172.00,2023-10,172.50,3717076
43,BRITANNIA,4538.45,2023-10-06 05:30:00,4549.45,4515.00,2023-10,4533.85,238131
44,SBILIFE,1282.95,2023-10-06 05:30:00,1287.55,1272.00,2023-10,1276.00,784191
45,HINDALCO,472.60,2023-10-06 05:30:00,476.45,469.35,2023-10,475.00,3134022
46,HEROMOTOCO,3038.00,2023-10-06 05:30:00,3045.00,3022.50,2023-10,3040.00,180660
47,AXISBANK,1000.95,2023-10-06 05:30:00,1008.00,999.40,2023-10,1005.00,5289753
48,HDFCBANK,1534.05,2023-10-06 05:30:00,1545.00,1529.85,2023-10,1544.00,8879678
49,BAJAJ-AUTO,5014.60,2023-10-06 05:30:00,5120.00,4997.50,2023-10,5120.00,279352

In [63]:
# Save the DataFrame as a CSV file
df.to_csv("D:/stock_csv/2023-10/2023-10-05_05-30-00", index=False)  # Replace with your desired CSV output path

print("YAML data successfully converted to CSV!")

YAML data successfully converted to CSV!

In [65]:
import yaml
import pandas as pd

# Load the YAML file
with open("D:/New Proj/2023-10/2023-10-06_05-30-00.yaml", "r") as file:  # Replace with your YAML file path
    data = yaml.safe_load(file)

# Convert the YAML data to a DataFrame
df = pd.DataFrame(data)

# Save the DataFrame as a CSV file
df.to_csv("D:/New Proj/output.csv", index=False)  # Replace with your desired CSV output path

print("YAML data successfully converted to CSV!")

YAML data successfully converted to CSV!

In [67]:
df

,Ticker,close,date,high,low,month,open,volume
0,SBIN,594.25,2023-10-06 05:30:00,598.95,592.20,2023-10,593.40,8216780
1,BAJFINANCE,8168.55,2023-10-06 05:30:00,8192.00,7845.00,2023-10,7850.00,2145034
2,TITAN,3309.75,2023-10-06 05:30:00,3319.80,3221.10,2023-10,3230.00,1102120
3,ITC,442.15,2023-10-06 05:30:00,443.60,436.65,2023-10,437.85,8418580
4,TCS,3621.40,2023-10-06 05:30:00,3634.95,3575.05,2023-10,3591.00,2075691
5,LT,3093.70,2023-10-06 05:30:00,3114.95,3073.15,2023-10,3114.95,1898118
6,TATACONSUM,864.01,2023-10-06 05:30:00,866.73,850.43,2023-10,850.43,948330
7,RELIANCE,1159.00,2023-10-06 05:30:00,1162.40,1156.03,2023-10,1158.53,5431026
8,HCLTECH,1237.70,2023-10-06 05:30:00,1256.00,1230.10,2023-10,1252.00,2497711
9,JSWSTEEL,765.20,2023-10-06 05:30:00,771.15,758.65,2023-10,760.35,2026927
10,ULTRACEMCO,8195.45,2023-10-06 05:30:00,8239.65,8151.25,2023-10,8198.00,158491
11,POWERGRID,197.05,2023-10-06 05:30:00,197.45,194.85,2023-10,197.00,12857229
12,INFY,1478.70,2023-10-06 05:30:00,1484.50,1463.30,2023-10,1469.50,3598672
13,TRENT,2072.10,2023-10-06 05:30:00,2091.90,2050.10,2023-10,2055.85,444220
14,BHARTIARTL,926.05,2023-10-06 05:30:00,929.20,924.30,2023-10,929.20,2420855
15,TATAMOTORS,622.45,2023-10-06 05:30:00,627.35,620.00,2023-10,627.00,7922379
16,WIPRO,407.85,2023-10-06 05:30:00,409.80,406.95,2023-10,408.00,3182502
17,TECHM,1216.90,2023-10-06 05:30:00,1223.00,1205.00,2023-10,1207.00,1446719
18,NTPC,235.55,2023-10-06 05:30:00,237.50,233.65,2023-10,234.25,8825123
19,HINDUNILVR,2499.40,2023-10-06 05:30:00,2520.00,2494.00,2023-10,2519.95,1083342
20,APOLLOHOSP,5060.25,2023-10-06 05:30:00,5084.00,5028.80,2023-10,5050.00,407753
21,M&M,1548.85,2023-10-06 05:30:00,1554.00,1540.35,2023-10,1545.00,1743027
22,GRASIM,1895.76,2023-10-06 05:30:00,1898.35,1882.52,2023-10,1882.62,399766
23,ICICIBANK,945.20,2023-10-06 05:30:00,946.55,938.00,2023-10,946.00,6355755
24,ADANIENT,2478.10,2023-10-06 05:30:00,2514.95,2466.05,2023-10,2466.35,1510035
25,ADANIPORTS,830.75,2023-10-06 05:30:00,836.50,826.40,2023-10,830.00,1877058
26,BEL,139.00,2023-10-06 05:30:00,140.50,138.65,2023-10,139.00,4987359
27,BAJAJFINSV,1634.65,2023-10-06 05:30:00,1640.70,1551.05,2023-10,1559.35,7384628
28,EICHERMOT,3450.40,2023-10-06 05:30:00,3464.45,3438.35,2023-10,3443.60,249258
29,COALINDIA,287.80,2023-10-06 05:30:00,291.00,287.00,2023-10,290.95,3741467
30,MARUTI,10302.00,2023-10-06 05:30:00,10333.00,10260.00,2023-10,10283.00,335700
31,INDUSINDBK,1434.80,2023-10-06 05:30:00,1438.00,1401.10,2023-10,1404.95,2167139
32,ASIANPAINT,3195.75,2023-10-06 05:30:00,3217.00,3190.00,2023-10,3214.75,814257
33,TATASTEEL,125.90,2023-10-06 05:30:00,127.00,125.10,2023-10,126.50,21928671
34,HDFCLIFE,630.90,2023-10-06 05:30:00,636.20,622.75,2023-10,624.55,3713370
35,DRREDDY,1084.98,2023-10-06 05:30:00,1097.44,1081.84,2023-10,1087.00,1572990
36,SUNPHARMA,1127.30,2023-10-06 05:30:00,1132.15,1123.10,2023-10,1128.00,1056281
37,KOTAKBANK,1743.90,2023-10-06 05:30:00,1747.00,1730.20,2023-10,1735.30,1992323
38,SHRIRAMFIN,1848.85,2023-10-06 05:30:00,1863.00,1835.00,2023-10,1850.95,1262390
39,NESTLEIND,2291.23,2023-10-06 05:30:00,2306.76,2281.49,2023-10,2298.99,388120
40,ONGC,181.45,2023-10-06 05:30:00,183.50,180.60,2023-10,183.50,5759904
41,CIPLA,1163.00,2023-10-06 05:30:00,1181.70,1160.45,2023-10,1165.00,928951
42,BPCL,173.60,2023-10-06 05:30:00,174.50,172.00,2023-10,172.50,3717076
43,BRITANNIA,4538.45,2023-10-06 05:30:00,4549.45,4515.00,2023-10,4533.85,238131
44,SBILIFE,1282.95,2023-10-06 05:30:00,1287.55,1272.00,2023-10,1276.00,784191
45,HINDALCO,472.60,2023-10-06 05:30:00,476.45,469.35,2023-10,475.00,3134022
46,HEROMOTOCO,3038.00,2023-10-06 05:30:00,3045.00,3022.50,2023-10,3040.00,180660
47,AXISBANK,1000.95,2023-10-06 05:30:00,1008.00,999.40,2023-10,1005.00,5289753
48,HDFCBANK,1534.05,2023-10-06 05:30:00,1545.00,1529.85,2023-10,1544.00,8879678
49,BAJAJ-AUTO,5014.60,2023-10-06 05:30:00,5120.00,4997.50,2023-10,5120.00,279352

In [69]:
# Save the DataFrame as a CSV file
df.to_csv("D:/stock_csv/2023-10/2023-10-06_05-30-00", index=False)  # Replace with your desired CSV output path

print("YAML data successfully converted to CSV!")

YAML data successfully converted to CSV!

In [71]:
import os
import yaml
import pandas as pd

# Define input and output directories
input_dir = "D:/New Proj/2023-10"  # Folder containing YAML files
output_dir = "D:/CSV_files/2023-10"  # Folder to save CSV files

# Ensure output directory exists
os.makedirs(output_dir, exist_ok=True)

# Iterate through all YAML files in the input directory
for file_name in os.listdir(input_dir):
    if file_name.endswith(".yaml"):
        input_path = os.path.join(input_dir, file_name)
        
        # Load the YAML file
        with open(input_path, "r") as file:
            data = yaml.safe_load(file)

        # Convert YAML to DataFrame
        df = pd.DataFrame(data)

        # Save the DataFrame as a CSV file
        output_file_name = file_name.replace(".yaml", ".csv")
        output_path = os.path.join(output_dir, output_file_name)
        df.to_csv(output_path, index=False)

        print(f"Converted {file_name} to {output_file_name}")

print("Batch conversion of YAML files to CSV completed!")

Converted 2023-10-03_05-30-00.yaml to 2023-10-03_05-30-00.csv
Converted 2023-10-04_05-30-00.yaml to 2023-10-04_05-30-00.csv
Converted 2023-10-05_05-30-00.yaml to 2023-10-05_05-30-00.csv
Converted 2023-10-06_05-30-00.yaml to 2023-10-06_05-30-00.csv
Converted 2023-10-09_05-30-00.yaml to 2023-10-09_05-30-00.csv
Converted 2023-10-10_05-30-00.yaml to 2023-10-10_05-30-00.csv
Converted 2023-10-11_05-30-00.yaml to 2023-10-11_05-30-00.csv
Converted 2023-10-12_05-30-00.yaml to 2023-10-12_05-30-00.csv
Converted 2023-10-13_05-30-00.yaml to 2023-10-13_05-30-00.csv
Converted 2023-10-16_05-30-00.yaml to 2023-10-16_05-30-00.csv
Converted 2023-10-17_05-30-00.yaml to 2023-10-17_05-30-00.csv
Converted 2023-10-18_05-30-00.yaml to 2023-10-18_05-30-00.csv
Converted 2023-10-19_05-30-00.yaml to 2023-10-19_05-30-00.csv
Converted 2023-10-20_05-30-00.yaml to 2023-10-20_05-30-00.csv
Converted 2023-10-23_05-30-00.yaml to 2023-10-23_05-30-00.csv
Converted 2023-10-25_05-30-00.yaml to 2023-10-25_05-30-00.csv
Converted 2023-10-26_05-30-00.yaml to 2023-10-26_05-30-00.csv
Converted 2023-10-27_05-30-00.yaml to 2023-10-27_05-30-00.csv
Converted 2023-10-30_05-30-00.yaml to 2023-10-30_05-30-00.csv
Converted 2023-10-31_05-30-00.yaml to 2023-10-31_05-30-00.csv
Batch conversion of YAML files to CSV completed!

In [73]:
import os
import yaml
import pandas as pd

# Define input and output directories
input_dir = "D:/New Proj/2023-11"  # Folder containing YAML files
output_dir = "D:/CSV_files/2023-11"  # Folder to save CSV files

# Ensure output directory exists
os.makedirs(output_dir, exist_ok=True)

# Iterate through all YAML files in the input directory
for file_name in os.listdir(input_dir):
    if file_name.endswith(".yaml"):
        input_path = os.path.join(input_dir, file_name)
        
        # Load the YAML file
        with open(input_path, "r") as file:
            data = yaml.safe_load(file)

        # Convert YAML to DataFrame
        df = pd.DataFrame(data)

        # Save the DataFrame as a CSV file
        output_file_name = file_name.replace(".yaml", ".csv")
        output_path = os.path.join(output_dir, output_file_name)
        df.to_csv(output_path, index=False)

        print(f"Converted {file_name} to {output_file_name}")

print("Batch conversion of YAML files to CSV completed!")

Converted 2023-11-01_05-30-00.yaml to 2023-11-01_05-30-00.csv
Converted 2023-11-02_05-30-00.yaml to 2023-11-02_05-30-00.csv
Converted 2023-11-03_05-30-00.yaml to 2023-11-03_05-30-00.csv
Converted 2023-11-06_05-30-00.yaml to 2023-11-06_05-30-00.csv
Converted 2023-11-07_05-30-00.yaml to 2023-11-07_05-30-00.csv
Converted 2023-11-08_05-30-00.yaml to 2023-11-08_05-30-00.csv
Converted 2023-11-09_05-30-00.yaml to 2023-11-09_05-30-00.csv
Converted 2023-11-10_05-30-00.yaml to 2023-11-10_05-30-00.csv
Converted 2023-11-12_05-30-00.yaml to 2023-11-12_05-30-00.csv
Converted 2023-11-13_05-30-00.yaml to 2023-11-13_05-30-00.csv
Converted 2023-11-15_05-30-00.yaml to 2023-11-15_05-30-00.csv
Converted 2023-11-16_05-30-00.yaml to 2023-11-16_05-30-00.csv
Converted 2023-11-17_05-30-00.yaml to 2023-11-17_05-30-00.csv
Converted 2023-11-20_05-30-00.yaml to 2023-11-20_05-30-00.csv
Converted 2023-11-21_05-30-00.yaml to 2023-11-21_05-30-00.csv
Converted 2023-11-22_05-30-00.yaml to 2023-11-22_05-30-00.csv
Converted 2023-11-23_05-30-00.yaml to 2023-11-23_05-30-00.csv
Converted 2023-11-24_05-30-00.yaml to 2023-11-24_05-30-00.csv
Converted 2023-11-28_05-30-00.yaml to 2023-11-28_05-30-00.csv
Converted 2023-11-29_05-30-00.yaml to 2023-11-29_05-30-00.csv
Converted 2023-11-30_05-30-00.yaml to 2023-11-30_05-30-00.csv
Batch conversion of YAML files to CSV completed!

In [75]:

# Define input and output directories
input_dir = "D:/New Proj/2023-12"  # Folder containing YAML files
output_dir = "D:/CSV_files/2023-12"  # Folder to save CSV files

# Ensure output directory exists
os.makedirs(output_dir, exist_ok=True)

# Iterate through all YAML files in the input directory
for file_name in os.listdir(input_dir):
    if file_name.endswith(".yaml"):
        input_path = os.path.join(input_dir, file_name)
        
        # Load the YAML file
        with open(input_path, "r") as file:
            data = yaml.safe_load(file)

        # Convert YAML to DataFrame
        df = pd.DataFrame(data)

        # Save the DataFrame as a CSV file
        output_file_name = file_name.replace(".yaml", ".csv")
        output_path = os.path.join(output_dir, output_file_name)
        df.to_csv(output_path, index=False)

        print(f"Converted {file_name} to {output_file_name}")

print("Batch conversion of YAML files to CSV completed!")

Converted 2023-12-01_05-30-00.yaml to 2023-12-01_05-30-00.csv
Converted 2023-12-04_05-30-00.yaml to 2023-12-04_05-30-00.csv
Converted 2023-12-05_05-30-00.yaml to 2023-12-05_05-30-00.csv
Converted 2023-12-06_05-30-00.yaml to 2023-12-06_05-30-00.csv
Converted 2023-12-07_05-30-00.yaml to 2023-12-07_05-30-00.csv
Converted 2023-12-08_05-30-00.yaml to 2023-12-08_05-30-00.csv
Converted 2023-12-11_05-30-00.yaml to 2023-12-11_05-30-00.csv
Converted 2023-12-12_05-30-00.yaml to 2023-12-12_05-30-00.csv
Converted 2023-12-13_05-30-00.yaml to 2023-12-13_05-30-00.csv
Converted 2023-12-14_05-30-00.yaml to 2023-12-14_05-30-00.csv
Converted 2023-12-15_05-30-00.yaml to 2023-12-15_05-30-00.csv
Converted 2023-12-18_05-30-00.yaml to 2023-12-18_05-30-00.csv
Converted 2023-12-19_05-30-00.yaml to 2023-12-19_05-30-00.csv
Converted 2023-12-20_05-30-00.yaml to 2023-12-20_05-30-00.csv
Converted 2023-12-21_05-30-00.yaml to 2023-12-21_05-30-00.csv
Converted 2023-12-22_05-30-00.yaml to 2023-12-22_05-30-00.csv
Converted 2023-12-26_05-30-00.yaml to 2023-12-26_05-30-00.csv
Converted 2023-12-27_05-30-00.yaml to 2023-12-27_05-30-00.csv
Converted 2023-12-28_05-30-00.yaml to 2023-12-28_05-30-00.csv
Converted 2023-12-29_05-30-00.yaml to 2023-12-29_05-30-00.csv
Batch conversion of YAML files to CSV completed!

In [77]:

# Define input and output directories
input_dir = "D:/New Proj/2024-01"  # Folder containing YAML files
output_dir = "D:/CSV_files/2024-01"  # Folder to save CSV files

# Ensure output directory exists
os.makedirs(output_dir, exist_ok=True)

# Iterate through all YAML files in the input directory
for file_name in os.listdir(input_dir):
    if file_name.endswith(".yaml"):
        input_path = os.path.join(input_dir, file_name)
        
        # Load the YAML file
        with open(input_path, "r") as file:
            data = yaml.safe_load(file)

        # Convert YAML to DataFrame
        df = pd.DataFrame(data)

        # Save the DataFrame as a CSV file
        output_file_name = file_name.replace(".yaml", ".csv")
        output_path = os.path.join(output_dir, output_file_name)
        df.to_csv(output_path, index=False)

        print(f"Converted {file_name} to {output_file_name}")

print("Batch conversion of YAML files to CSV completed!")

Converted 2024-01-01_05-30-00.yaml to 2024-01-01_05-30-00.csv
Converted 2024-01-02_05-30-00.yaml to 2024-01-02_05-30-00.csv
Converted 2024-01-03_05-30-00.yaml to 2024-01-03_05-30-00.csv
Converted 2024-01-04_05-30-00.yaml to 2024-01-04_05-30-00.csv
Converted 2024-01-05_05-30-00.yaml to 2024-01-05_05-30-00.csv
Converted 2024-01-08_05-30-00.yaml to 2024-01-08_05-30-00.csv
Converted 2024-01-09_05-30-00.yaml to 2024-01-09_05-30-00.csv
Converted 2024-01-10_05-30-00.yaml to 2024-01-10_05-30-00.csv
Converted 2024-01-11_05-30-00.yaml to 2024-01-11_05-30-00.csv
Converted 2024-01-12_05-30-00.yaml to 2024-01-12_05-30-00.csv
Converted 2024-01-15_05-30-00.yaml to 2024-01-15_05-30-00.csv
Converted 2024-01-16_05-30-00.yaml to 2024-01-16_05-30-00.csv
Converted 2024-01-17_05-30-00.yaml to 2024-01-17_05-30-00.csv
Converted 2024-01-18_05-30-00.yaml to 2024-01-18_05-30-00.csv
Converted 2024-01-19_05-30-00.yaml to 2024-01-19_05-30-00.csv
Converted 2024-01-20_05-30-00.yaml to 2024-01-20_05-30-00.csv
Converted 2024-01-23_05-30-00.yaml to 2024-01-23_05-30-00.csv
Converted 2024-01-24_05-30-00.yaml to 2024-01-24_05-30-00.csv
Converted 2024-01-25_05-30-00.yaml to 2024-01-25_05-30-00.csv
Converted 2024-01-29_05-30-00.yaml to 2024-01-29_05-30-00.csv
Converted 2024-01-30_05-30-00.yaml to 2024-01-30_05-30-00.csv
Converted 2024-01-31_05-30-00.yaml to 2024-01-31_05-30-00.csv
Batch conversion of YAML files to CSV completed!

In [79]:
# Define input and output directories
input_dir = "D:/New Proj/2024-02"  # Folder containing YAML files
output_dir = "D:/CSV_files/2024-02"  # Folder to save CSV files

# Ensure output directory exists
os.makedirs(output_dir, exist_ok=True)

# Iterate through all YAML files in the input directory
for file_name in os.listdir(input_dir):
    if file_name.endswith(".yaml"):
        input_path = os.path.join(input_dir, file_name)
        
        # Load the YAML file
        with open(input_path, "r") as file:
            data = yaml.safe_load(file)

        # Convert YAML to DataFrame
        df = pd.DataFrame(data)

        # Save the DataFrame as a CSV file
        output_file_name = file_name.replace(".yaml", ".csv")
        output_path = os.path.join(output_dir, output_file_name)
        df.to_csv(output_path, index=False)

        print(f"Converted {file_name} to {output_file_name}")

print("Batch conversion of YAML files to CSV completed!")

Converted 2024-02-01_05-30-00.yaml to 2024-02-01_05-30-00.csv
Converted 2024-02-02_05-30-00.yaml to 2024-02-02_05-30-00.csv
Converted 2024-02-05_05-30-00.yaml to 2024-02-05_05-30-00.csv
Converted 2024-02-06_05-30-00.yaml to 2024-02-06_05-30-00.csv
Converted 2024-02-07_05-30-00.yaml to 2024-02-07_05-30-00.csv
Converted 2024-02-08_05-30-00.yaml to 2024-02-08_05-30-00.csv
Converted 2024-02-09_05-30-00.yaml to 2024-02-09_05-30-00.csv
Converted 2024-02-12_05-30-00.yaml to 2024-02-12_05-30-00.csv
Converted 2024-02-13_05-30-00.yaml to 2024-02-13_05-30-00.csv
Converted 2024-02-14_05-30-00.yaml to 2024-02-14_05-30-00.csv
Converted 2024-02-15_05-30-00.yaml to 2024-02-15_05-30-00.csv
Converted 2024-02-16_05-30-00.yaml to 2024-02-16_05-30-00.csv
Converted 2024-02-19_05-30-00.yaml to 2024-02-19_05-30-00.csv
Converted 2024-02-20_05-30-00.yaml to 2024-02-20_05-30-00.csv
Converted 2024-02-21_05-30-00.yaml to 2024-02-21_05-30-00.csv
Converted 2024-02-22_05-30-00.yaml to 2024-02-22_05-30-00.csv
Converted 2024-02-23_05-30-00.yaml to 2024-02-23_05-30-00.csv
Converted 2024-02-26_05-30-00.yaml to 2024-02-26_05-30-00.csv
Converted 2024-02-27_05-30-00.yaml to 2024-02-27_05-30-00.csv
Converted 2024-02-28_05-30-00.yaml to 2024-02-28_05-30-00.csv
Converted 2024-02-29_05-30-00.yaml to 2024-02-29_05-30-00.csv
Batch conversion of YAML files to CSV completed!

In [81]:
# Define input and output directories
input_dir = "D:/New Proj/2024-03"  # Folder containing YAML files
output_dir = "D:/CSV_files/2024-03"  # Folder to save CSV files

# Ensure output directory exists
os.makedirs(output_dir, exist_ok=True)

# Iterate through all YAML files in the input directory
for file_name in os.listdir(input_dir):
    if file_name.endswith(".yaml"):
        input_path = os.path.join(input_dir, file_name)
        
        # Load the YAML file
        with open(input_path, "r") as file:
            data = yaml.safe_load(file)

        # Convert YAML to DataFrame
        df = pd.DataFrame(data)

        # Save the DataFrame as a CSV file
        output_file_name = file_name.replace(".yaml", ".csv")
        output_path = os.path.join(output_dir, output_file_name)
        df.to_csv(output_path, index=False)

        print(f"Converted {file_name} to {output_file_name}")

print("Batch conversion of YAML files to CSV completed!")

Converted 2024-03-01_05-30-00.yaml to 2024-03-01_05-30-00.csv
Converted 2024-03-02_05-30-00.yaml to 2024-03-02_05-30-00.csv
Converted 2024-03-04_05-30-00.yaml to 2024-03-04_05-30-00.csv
Converted 2024-03-05_05-30-00.yaml to 2024-03-05_05-30-00.csv
Converted 2024-03-06_05-30-00.yaml to 2024-03-06_05-30-00.csv
Converted 2024-03-07_05-30-00.yaml to 2024-03-07_05-30-00.csv
Converted 2024-03-11_05-30-00.yaml to 2024-03-11_05-30-00.csv
Converted 2024-03-12_05-30-00.yaml to 2024-03-12_05-30-00.csv
Converted 2024-03-13_05-30-00.yaml to 2024-03-13_05-30-00.csv
Converted 2024-03-14_05-30-00.yaml to 2024-03-14_05-30-00.csv
Converted 2024-03-15_05-30-00.yaml to 2024-03-15_05-30-00.csv
Converted 2024-03-18_05-30-00.yaml to 2024-03-18_05-30-00.csv
Converted 2024-03-19_05-30-00.yaml to 2024-03-19_05-30-00.csv
Converted 2024-03-20_05-30-00.yaml to 2024-03-20_05-30-00.csv
Converted 2024-03-21_05-30-00.yaml to 2024-03-21_05-30-00.csv
Converted 2024-03-22_05-30-00.yaml to 2024-03-22_05-30-00.csv
Converted 2024-03-26_05-30-00.yaml to 2024-03-26_05-30-00.csv
Converted 2024-03-27_05-30-00.yaml to 2024-03-27_05-30-00.csv
Converted 2024-03-28_05-30-00.yaml to 2024-03-28_05-30-00.csv
Batch conversion of YAML files to CSV completed!

In [83]:
# Define input and output directories
input_dir = "D:/New Proj/2024-04"  # Folder containing YAML files
output_dir = "D:/CSV_files/2024-04"  # Folder to save CSV files

# Ensure output directory exists
os.makedirs(output_dir, exist_ok=True)

# Iterate through all YAML files in the input directory
for file_name in os.listdir(input_dir):
    if file_name.endswith(".yaml"):
        input_path = os.path.join(input_dir, file_name)
        
        # Load the YAML file
        with open(input_path, "r") as file:
            data = yaml.safe_load(file)

        # Convert YAML to DataFrame
        df = pd.DataFrame(data)

        # Save the DataFrame as a CSV file
        output_file_name = file_name.replace(".yaml", ".csv")
        output_path = os.path.join(output_dir, output_file_name)
        df.to_csv(output_path, index=False)

        print(f"Converted {file_name} to {output_file_name}")

print("Batch conversion of YAML files to CSV completed!")

Converted 2024-04-01_05-30-00.yaml to 2024-04-01_05-30-00.csv
Converted 2024-04-02_05-30-00.yaml to 2024-04-02_05-30-00.csv
Converted 2024-04-03_05-30-00.yaml to 2024-04-03_05-30-00.csv
Converted 2024-04-04_05-30-00.yaml to 2024-04-04_05-30-00.csv
Converted 2024-04-05_05-30-00.yaml to 2024-04-05_05-30-00.csv
Converted 2024-04-08_05-30-00.yaml to 2024-04-08_05-30-00.csv
Converted 2024-04-09_05-30-00.yaml to 2024-04-09_05-30-00.csv
Converted 2024-04-10_05-30-00.yaml to 2024-04-10_05-30-00.csv
Converted 2024-04-12_05-30-00.yaml to 2024-04-12_05-30-00.csv
Converted 2024-04-15_05-30-00.yaml to 2024-04-15_05-30-00.csv
Converted 2024-04-16_05-30-00.yaml to 2024-04-16_05-30-00.csv
Converted 2024-04-18_05-30-00.yaml to 2024-04-18_05-30-00.csv
Converted 2024-04-19_05-30-00.yaml to 2024-04-19_05-30-00.csv
Converted 2024-04-22_05-30-00.yaml to 2024-04-22_05-30-00.csv
Converted 2024-04-23_05-30-00.yaml to 2024-04-23_05-30-00.csv
Converted 2024-04-24_05-30-00.yaml to 2024-04-24_05-30-00.csv
Converted 2024-04-25_05-30-00.yaml to 2024-04-25_05-30-00.csv
Converted 2024-04-26_05-30-00.yaml to 2024-04-26_05-30-00.csv
Converted 2024-04-29_05-30-00.yaml to 2024-04-29_05-30-00.csv
Converted 2024-04-30_05-30-00.yaml to 2024-04-30_05-30-00.csv
Batch conversion of YAML files to CSV completed!

In [87]:
# Define input and output directories
input_dir = "D:/New Proj/2024-05"  # Folder containing YAML files
output_dir = "D:/CSV_files/2024-05"  # Folder to save CSV files

# Ensure output directory exists
os.makedirs(output_dir, exist_ok=True)

# Iterate through all YAML files in the input directory
for file_name in os.listdir(input_dir):
    if file_name.endswith(".yaml"):
        input_path = os.path.join(input_dir, file_name)
        
        # Load the YAML file
        with open(input_path, "r") as file:
            data = yaml.safe_load(file)

        # Convert YAML to DataFrame
        df = pd.DataFrame(data)

        # Save the DataFrame as a CSV file
        output_file_name = file_name.replace(".yaml", ".csv")
        output_path = os.path.join(output_dir, output_file_name)
        df.to_csv(output_path, index=False)

        print(f"Converted {file_name} to {output_file_name}")

print("Batch conversion of YAML files to CSV completed!")

Converted 2024-05-02_05-30-00.yaml to 2024-05-02_05-30-00.csv
Converted 2024-05-03_05-30-00.yaml to 2024-05-03_05-30-00.csv
Converted 2024-05-06_05-30-00.yaml to 2024-05-06_05-30-00.csv
Converted 2024-05-07_05-30-00.yaml to 2024-05-07_05-30-00.csv
Converted 2024-05-08_05-30-00.yaml to 2024-05-08_05-30-00.csv
Converted 2024-05-09_05-30-00.yaml to 2024-05-09_05-30-00.csv
Converted 2024-05-10_05-30-00.yaml to 2024-05-10_05-30-00.csv
Converted 2024-05-13_05-30-00.yaml to 2024-05-13_05-30-00.csv
Converted 2024-05-14_05-30-00.yaml to 2024-05-14_05-30-00.csv
Converted 2024-05-15_05-30-00.yaml to 2024-05-15_05-30-00.csv
Converted 2024-05-16_05-30-00.yaml to 2024-05-16_05-30-00.csv
Converted 2024-05-17_05-30-00.yaml to 2024-05-17_05-30-00.csv
Converted 2024-05-18_05-30-00.yaml to 2024-05-18_05-30-00.csv
Converted 2024-05-21_05-30-00.yaml to 2024-05-21_05-30-00.csv
Converted 2024-05-22_05-30-00.yaml to 2024-05-22_05-30-00.csv
Converted 2024-05-23_05-30-00.yaml to 2024-05-23_05-30-00.csv
Converted 2024-05-24_05-30-00.yaml to 2024-05-24_05-30-00.csv
Converted 2024-05-27_05-30-00.yaml to 2024-05-27_05-30-00.csv
Converted 2024-05-28_05-30-00.yaml to 2024-05-28_05-30-00.csv
Converted 2024-05-29_05-30-00.yaml to 2024-05-29_05-30-00.csv
Converted 2024-05-30_05-30-00.yaml to 2024-05-30_05-30-00.csv
Converted 2024-05-31_05-30-00.yaml to 2024-05-31_05-30-00.csv
Batch conversion of YAML files to CSV completed!

In [89]:
# Define input and output directories
input_dir = "D:/New Proj/2024-06"  # Folder containing YAML files
output_dir = "D:/CSV_files/2024-06"  # Folder to save CSV files

# Ensure output directory exists
os.makedirs(output_dir, exist_ok=True)

# Iterate through all YAML files in the input directory
for file_name in os.listdir(input_dir):
    if file_name.endswith(".yaml"):
        input_path = os.path.join(input_dir, file_name)
        
        # Load the YAML file
        with open(input_path, "r") as file:
            data = yaml.safe_load(file)

        # Convert YAML to DataFrame
        df = pd.DataFrame(data)

        # Save the DataFrame as a CSV file
        output_file_name = file_name.replace(".yaml", ".csv")
        output_path = os.path.join(output_dir, output_file_name)
        df.to_csv(output_path, index=False)

        print(f"Converted {file_name} to {output_file_name}")

print("Batch conversion of YAML files to CSV completed!")

Converted 2024-06-03_05-30-00.yaml to 2024-06-03_05-30-00.csv
Converted 2024-06-04_05-30-00.yaml to 2024-06-04_05-30-00.csv
Converted 2024-06-05_05-30-00.yaml to 2024-06-05_05-30-00.csv
Converted 2024-06-06_05-30-00.yaml to 2024-06-06_05-30-00.csv
Converted 2024-06-07_05-30-00.yaml to 2024-06-07_05-30-00.csv
Converted 2024-06-10_05-30-00.yaml to 2024-06-10_05-30-00.csv
Converted 2024-06-11_05-30-00.yaml to 2024-06-11_05-30-00.csv
Converted 2024-06-12_05-30-00.yaml to 2024-06-12_05-30-00.csv
Converted 2024-06-13_05-30-00.yaml to 2024-06-13_05-30-00.csv
Converted 2024-06-14_05-30-00.yaml to 2024-06-14_05-30-00.csv
Converted 2024-06-18_05-30-00.yaml to 2024-06-18_05-30-00.csv
Converted 2024-06-19_05-30-00.yaml to 2024-06-19_05-30-00.csv
Converted 2024-06-20_05-30-00.yaml to 2024-06-20_05-30-00.csv
Converted 2024-06-21_05-30-00.yaml to 2024-06-21_05-30-00.csv
Converted 2024-06-24_05-30-00.yaml to 2024-06-24_05-30-00.csv
Converted 2024-06-25_05-30-00.yaml to 2024-06-25_05-30-00.csv
Converted 2024-06-26_05-30-00.yaml to 2024-06-26_05-30-00.csv
Converted 2024-06-27_05-30-00.yaml to 2024-06-27_05-30-00.csv
Converted 2024-06-28_05-30-00.yaml to 2024-06-28_05-30-00.csv
Batch conversion of YAML files to CSV completed!

In [91]:
# Define input and output directories
input_dir = "D:/New Proj/2024-07"  # Folder containing YAML files
output_dir = "D:/CSV_files/2024-07"  # Folder to save CSV files

# Ensure output directory exists
os.makedirs(output_dir, exist_ok=True)

# Iterate through all YAML files in the input directory
for file_name in os.listdir(input_dir):
    if file_name.endswith(".yaml"):
        input_path = os.path.join(input_dir, file_name)
        
        # Load the YAML file
        with open(input_path, "r") as file:
            data = yaml.safe_load(file)

        # Convert YAML to DataFrame
        df = pd.DataFrame(data)

        # Save the DataFrame as a CSV file
        output_file_name = file_name.replace(".yaml", ".csv")
        output_path = os.path.join(output_dir, output_file_name)
        df.to_csv(output_path, index=False)

        print(f"Converted {file_name} to {output_file_name}")

print("Batch conversion of YAML files to CSV completed!")

Converted 2024-07-01_05-30-00.yaml to 2024-07-01_05-30-00.csv
Converted 2024-07-02_05-30-00.yaml to 2024-07-02_05-30-00.csv
Converted 2024-07-03_05-30-00.yaml to 2024-07-03_05-30-00.csv
Converted 2024-07-04_05-30-00.yaml to 2024-07-04_05-30-00.csv
Converted 2024-07-05_05-30-00.yaml to 2024-07-05_05-30-00.csv
Converted 2024-07-08_05-30-00.yaml to 2024-07-08_05-30-00.csv
Converted 2024-07-09_05-30-00.yaml to 2024-07-09_05-30-00.csv
Converted 2024-07-10_05-30-00.yaml to 2024-07-10_05-30-00.csv
Converted 2024-07-11_05-30-00.yaml to 2024-07-11_05-30-00.csv
Converted 2024-07-12_05-30-00.yaml to 2024-07-12_05-30-00.csv
Converted 2024-07-15_05-30-00.yaml to 2024-07-15_05-30-00.csv
Converted 2024-07-16_05-30-00.yaml to 2024-07-16_05-30-00.csv
Converted 2024-07-18_05-30-00.yaml to 2024-07-18_05-30-00.csv
Converted 2024-07-19_05-30-00.yaml to 2024-07-19_05-30-00.csv
Converted 2024-07-22_05-30-00.yaml to 2024-07-22_05-30-00.csv
Converted 2024-07-23_05-30-00.yaml to 2024-07-23_05-30-00.csv
Converted 2024-07-24_05-30-00.yaml to 2024-07-24_05-30-00.csv
Converted 2024-07-25_05-30-00.yaml to 2024-07-25_05-30-00.csv
Converted 2024-07-26_05-30-00.yaml to 2024-07-26_05-30-00.csv
Converted 2024-07-29_05-30-00.yaml to 2024-07-29_05-30-00.csv
Converted 2024-07-30_05-30-00.yaml to 2024-07-30_05-30-00.csv
Converted 2024-07-31_05-30-00.yaml to 2024-07-31_05-30-00.csv
Batch conversion of YAML files to CSV completed!

In [93]:
# Define input and output directories
input_dir = "D:/New Proj/2024-08"  # Folder containing YAML files
output_dir = "D:/CSV_files/2024-08"  # Folder to save CSV files

# Ensure output directory exists
os.makedirs(output_dir, exist_ok=True)

# Iterate through all YAML files in the input directory
for file_name in os.listdir(input_dir):
    if file_name.endswith(".yaml"):
        input_path = os.path.join(input_dir, file_name)
        
        # Load the YAML file
        with open(input_path, "r") as file:
            data = yaml.safe_load(file)

        # Convert YAML to DataFrame
        df = pd.DataFrame(data)

        # Save the DataFrame as a CSV file
        output_file_name = file_name.replace(".yaml", ".csv")
        output_path = os.path.join(output_dir, output_file_name)
        df.to_csv(output_path, index=False)

        print(f"Converted {file_name} to {output_file_name}")

print("Batch conversion of YAML files to CSV completed!")

Converted 2024-08-01_05-30-00.yaml to 2024-08-01_05-30-00.csv
Converted 2024-08-02_05-30-00.yaml to 2024-08-02_05-30-00.csv
Converted 2024-08-05_05-30-00.yaml to 2024-08-05_05-30-00.csv
Converted 2024-08-06_05-30-00.yaml to 2024-08-06_05-30-00.csv
Converted 2024-08-07_05-30-00.yaml to 2024-08-07_05-30-00.csv
Converted 2024-08-08_05-30-00.yaml to 2024-08-08_05-30-00.csv
Converted 2024-08-09_05-30-00.yaml to 2024-08-09_05-30-00.csv
Converted 2024-08-12_05-30-00.yaml to 2024-08-12_05-30-00.csv
Converted 2024-08-13_05-30-00.yaml to 2024-08-13_05-30-00.csv
Converted 2024-08-14_05-30-00.yaml to 2024-08-14_05-30-00.csv
Converted 2024-08-16_05-30-00.yaml to 2024-08-16_05-30-00.csv
Converted 2024-08-19_05-30-00.yaml to 2024-08-19_05-30-00.csv
Converted 2024-08-20_05-30-00.yaml to 2024-08-20_05-30-00.csv
Converted 2024-08-21_05-30-00.yaml to 2024-08-21_05-30-00.csv
Converted 2024-08-22_05-30-00.yaml to 2024-08-22_05-30-00.csv
Converted 2024-08-23_05-30-00.yaml to 2024-08-23_05-30-00.csv
Converted 2024-08-26_05-30-00.yaml to 2024-08-26_05-30-00.csv
Converted 2024-08-27_05-30-00.yaml to 2024-08-27_05-30-00.csv
Converted 2024-08-28_05-30-00.yaml to 2024-08-28_05-30-00.csv
Converted 2024-08-29_05-30-00.yaml to 2024-08-29_05-30-00.csv
Converted 2024-08-30_05-30-00.yaml to 2024-08-30_05-30-00.csv
Batch conversion of YAML files to CSV completed!

In [95]:
# Define input and output directories
input_dir = "D:/New Proj/2024-09"  # Folder containing YAML files
output_dir = "D:/CSV_files/2024-09"  # Folder to save CSV files

# Ensure output directory exists
os.makedirs(output_dir, exist_ok=True)

# Iterate through all YAML files in the input directory
for file_name in os.listdir(input_dir):
    if file_name.endswith(".yaml"):
        input_path = os.path.join(input_dir, file_name)
        
        # Load the YAML file
        with open(input_path, "r") as file:
            data = yaml.safe_load(file)

        # Convert YAML to DataFrame
        df = pd.DataFrame(data)

        # Save the DataFrame as a CSV file
        output_file_name = file_name.replace(".yaml", ".csv")
        output_path = os.path.join(output_dir, output_file_name)
        df.to_csv(output_path, index=False)

        print(f"Converted {file_name} to {output_file_name}")

print("Batch conversion of YAML files to CSV completed!")

Converted 2024-09-02_05-30-00.yaml to 2024-09-02_05-30-00.csv
Converted 2024-09-03_05-30-00.yaml to 2024-09-03_05-30-00.csv
Converted 2024-09-04_05-30-00.yaml to 2024-09-04_05-30-00.csv
Converted 2024-09-05_05-30-00.yaml to 2024-09-05_05-30-00.csv
Converted 2024-09-06_05-30-00.yaml to 2024-09-06_05-30-00.csv
Converted 2024-09-09_05-30-00.yaml to 2024-09-09_05-30-00.csv
Converted 2024-09-10_05-30-00.yaml to 2024-09-10_05-30-00.csv
Converted 2024-09-11_05-30-00.yaml to 2024-09-11_05-30-00.csv
Converted 2024-09-12_05-30-00.yaml to 2024-09-12_05-30-00.csv
Converted 2024-09-13_05-30-00.yaml to 2024-09-13_05-30-00.csv
Converted 2024-09-16_05-30-00.yaml to 2024-09-16_05-30-00.csv
Converted 2024-09-17_05-30-00.yaml to 2024-09-17_05-30-00.csv
Converted 2024-09-18_05-30-00.yaml to 2024-09-18_05-30-00.csv
Converted 2024-09-19_05-30-00.yaml to 2024-09-19_05-30-00.csv
Converted 2024-09-20_05-30-00.yaml to 2024-09-20_05-30-00.csv
Converted 2024-09-23_05-30-00.yaml to 2024-09-23_05-30-00.csv
Converted 2024-09-24_05-30-00.yaml to 2024-09-24_05-30-00.csv
Converted 2024-09-25_05-30-00.yaml to 2024-09-25_05-30-00.csv
Converted 2024-09-26_05-30-00.yaml to 2024-09-26_05-30-00.csv
Converted 2024-09-27_05-30-00.yaml to 2024-09-27_05-30-00.csv
Converted 2024-09-30_05-30-00.yaml to 2024-09-30_05-30-00.csv
Batch conversion of YAML files to CSV completed!

In [97]:
# Define input and output directories
input_dir = "D:/New Proj/2024-10"  # Folder containing YAML files
output_dir = "D:/CSV_files/2024-10"  # Folder to save CSV files

# Ensure output directory exists
os.makedirs(output_dir, exist_ok=True)

# Iterate through all YAML files in the input directory
for file_name in os.listdir(input_dir):
    if file_name.endswith(".yaml"):
        input_path = os.path.join(input_dir, file_name)
        
        # Load the YAML file
        with open(input_path, "r") as file:
            data = yaml.safe_load(file)

        # Convert YAML to DataFrame
        df = pd.DataFrame(data)

        # Save the DataFrame as a CSV file
        output_file_name = file_name.replace(".yaml", ".csv")
        output_path = os.path.join(output_dir, output_file_name)
        df.to_csv(output_path, index=False)

        print(f"Converted {file_name} to {output_file_name}")

print("Batch conversion of YAML files to CSV completed!")

Converted 2024-10-01_05-30-00.yaml to 2024-10-01_05-30-00.csv
Converted 2024-10-03_05-30-00.yaml to 2024-10-03_05-30-00.csv
Converted 2024-10-04_05-30-00.yaml to 2024-10-04_05-30-00.csv
Converted 2024-10-07_05-30-00.yaml to 2024-10-07_05-30-00.csv
Converted 2024-10-08_05-30-00.yaml to 2024-10-08_05-30-00.csv
Converted 2024-10-09_05-30-00.yaml to 2024-10-09_05-30-00.csv
Converted 2024-10-10_05-30-00.yaml to 2024-10-10_05-30-00.csv
Converted 2024-10-11_05-30-00.yaml to 2024-10-11_05-30-00.csv
Converted 2024-10-14_05-30-00.yaml to 2024-10-14_05-30-00.csv
Converted 2024-10-15_05-30-00.yaml to 2024-10-15_05-30-00.csv
Converted 2024-10-16_05-30-00.yaml to 2024-10-16_05-30-00.csv
Converted 2024-10-17_05-30-00.yaml to 2024-10-17_05-30-00.csv
Converted 2024-10-18_05-30-00.yaml to 2024-10-18_05-30-00.csv
Converted 2024-10-21_05-30-00.yaml to 2024-10-21_05-30-00.csv
Converted 2024-10-22_05-30-00.yaml to 2024-10-22_05-30-00.csv
Converted 2024-10-23_05-30-00.yaml to 2024-10-23_05-30-00.csv
Converted 2024-10-24_05-30-00.yaml to 2024-10-24_05-30-00.csv
Converted 2024-10-25_05-30-00.yaml to 2024-10-25_05-30-00.csv
Converted 2024-10-28_05-30-00.yaml to 2024-10-28_05-30-00.csv
Converted 2024-10-29_05-30-00.yaml to 2024-10-29_05-30-00.csv
Converted 2024-10-30_05-30-00.yaml to 2024-10-30_05-30-00.csv
Converted 2024-10-31_05-30-00.yaml to 2024-10-31_05-30-00.csv
Batch conversion of YAML files to CSV completed!

In [99]:
# Define input and output directories
input_dir = "D:/New Proj/2024-11"  # Folder containing YAML files
output_dir = "D:/CSV_files/2024-11"  # Folder to save CSV files

# Ensure output directory exists
os.makedirs(output_dir, exist_ok=True)

# Iterate through all YAML files in the input directory
for file_name in os.listdir(input_dir):
    if file_name.endswith(".yaml"):
        input_path = os.path.join(input_dir, file_name)
        
        # Load the YAML file
        with open(input_path, "r") as file:
            data = yaml.safe_load(file)

        # Convert YAML to DataFrame
        df = pd.DataFrame(data)

        # Save the DataFrame as a CSV file
        output_file_name = file_name.replace(".yaml", ".csv")
        output_path = os.path.join(output_dir, output_file_name)
        df.to_csv(output_path, index=False)

        print(f"Converted {file_name} to {output_file_name}")

print("Batch conversion of YAML files to CSV completed!")

Converted 2024-11-01_05-30-00.yaml to 2024-11-01_05-30-00.csv
Converted 2024-11-04_05-30-00.yaml to 2024-11-04_05-30-00.csv
Converted 2024-11-05_05-30-00.yaml to 2024-11-05_05-30-00.csv
Converted 2024-11-06_05-30-00.yaml to 2024-11-06_05-30-00.csv
Converted 2024-11-07_05-30-00.yaml to 2024-11-07_05-30-00.csv
Converted 2024-11-08_05-30-00.yaml to 2024-11-08_05-30-00.csv
Converted 2024-11-11_05-30-00.yaml to 2024-11-11_05-30-00.csv
Converted 2024-11-12_05-30-00.yaml to 2024-11-12_05-30-00.csv
Converted 2024-11-13_05-30-00.yaml to 2024-11-13_05-30-00.csv
Converted 2024-11-14_05-30-00.yaml to 2024-11-14_05-30-00.csv
Converted 2024-11-18_05-30-00.yaml to 2024-11-18_05-30-00.csv
Converted 2024-11-19_05-30-00.yaml to 2024-11-19_05-30-00.csv
Converted 2024-11-21_05-30-00.yaml to 2024-11-21_05-30-00.csv
Converted 2024-11-22_05-30-00.yaml to 2024-11-22_05-30-00.csv
Batch conversion of YAML files to CSV completed!